name: Build Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag yyarmoshyk/curl-docker-image:$(date +%s)
    - name: Tag the Docker image
      run: docker tag yyarmoshyk/curl-docker-image:$(date +%s) yyarmoshyk/curl-docker-image:latest
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: yyarmoshyk/curl-docker-image
        tag_with_ref: true
