name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag yyarmoshyk/curl-docker-image:$(date +%s)
    - name: Build the Docker image
      run: docker tag yyarmoshyk/curl-docker-image:$(date +%s) yyarmoshyk/curl-docker-image:latest
    - name: Publish the Docker image
      run: docker push yyarmoshyk/curl-docker-image:$(date +%s) && docker push yyarmoshyk/curl-docker-image:latest
