name: Build Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CURL_VERSION: "7.74.0"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --build-arg curl_version=$CURL_VERSION --tag yyarmoshyk/curl-docker-image:latest
      env:
        DOCKER_CONTENT_TRUST: 1
    - name: Scan
      uses: Azure/container-scan@v0
      with:
        image-name: yyarmoshyk/curl-docker-image:latest
    - name: Push to Docker Hub
      run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} && docker push yyarmoshyk/curl-docker-image:latest

  # Scan:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Scan image
  #     uses: sysdiglabs/scan-action@v1
  #     with:
  #       image-tag: "yyarmoshyk/curl-docker-image:latest"
  #       sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
